document.getElementById("myNav").innerHTML =
	"<div class='w3-top'>"
	+ "<div class='w3-bar w3-red w3-card w3-left-align w3-large'>"
	+ "<a class='w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red' href='javascript:void(0);' onclick='myFunction()' title='Toggle Navigation Menu'><i class='fa fa-bars'></i></a>"
    + "<a href='default.html' class='w3-bar-item w3-button w3-padding-large w3-hover-white'>Home</a>"
    + "<a href='offering_services.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Service</a>"
    + "<a href='Contact_us.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Contact</a>"
    + "<a href='About.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>About</a>"
    + "<a href='Prayer.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Prayer</a>"
    + "<a href='shop.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Shop</a>"
    + "<a href='blog.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Blog</a>"
    + "</div>"
    + "<div id='navDemo' class='w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large'>"
    + " <a href='offering_services.html' class='w3-bar-item w3-button w3-padding-large'>Service</a>"
    + "<a href='Contact_us.html' class='w3-bar-item w3-button w3-padding-large'>Contact</a>"
    + "<a href='About.html' class='w3-bar-item w3-button w3-padding-large'>About</a>"
    + "<a href='Prayer.html' class='w3-bar-item w3-button w3-padding-large'>Prayer</a>"
    + "<a href='shop.html' class='w3-bar-item w3-button w3-padding-large'>Shop</a>"
    + "<a href='blog.html' class='w3-bar-item w3-button w3-padding-large'>Blog</a>"
    + "</div>"
	+ "</div>";
document.getElementById("myFooter").innerHTML =    
	"<footer class=' w3-padding-64 w3-red'>"
    + "<div class='w3-row-padding'>"
    + "<div class='w3-third'>"
    + "<h3>Fraonds Technologies</h3>"
    + "<ul class='w3-ul'>"
    + "<li class='w3-padding-16'>"
    + "<img src='images/prist.JPG' class='w3-left w3-margin-right' style='width:50px'/>"
    + "</li>" 
    + "</ul><br>"
    + "<p>Provides on-demand services for its customers and collaboratively offer opportunities for local professionals; it’s the path to the freedoms of life.</p>" 
    + "</div>"
    + "<div class='w3-third'>"
    + "<h3>CONTACT US</h3>"
    + "<i class='fa fa-map-marker' style='width:30px'></i>Laxman Sastri 919 E. Lemo St. Tempe, AZ 85226<br>"
    + "<i class='fa fa-phone' style='width:30px'></i> Phone: +00 (602) 386-6807 <br>"
    + "<i class='fa fa-envelope' style='width:30px'> </i> Email: mail@mail.com<br>"
    + "</div>"
    + "<div class='w3-third'>"
    + "<h3>LINKS</h3>"
    + "<a href='default.html' class='w3-bar-item w3-button w3-padding-large w3-hover-white'>Home</a>"
    + "<a href='offering_services.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Service</a>"
    + "<a href='Contact_us.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Contact</a>"
    + "<a href='About.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>About</a>"
    + "<a href='Prayer.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Prayer</a>"
    + "<a href='shop.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Shop</a>"
    + "<a href='blog.html' class='w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white'>Blog</a>"
    + "</div>"
    + "<div class='w3-container w3-center'>" 
    + "<div class='w3-xlarge'>"
    + "<i class='fa fa-facebook-official w3-hover-opacity' style='width:30px'></i>"
    + "<i class='fa fa-instagram w3-hover-opacity' style='width:30px'></i>"
    + "<i class='fa fa-snapchat w3-hover-opacity' style='width:30px'></i>"
    + "<i class='fa fa-pinterest-p w3-hover-opacity' style='width:30px'></i>"
    + "<i class='fa fa-twitter w3-hover-opacity' style='width:30px'></i>"
    + "<i class='fa fa-linkedin w3-hover-opacity' style='width:30px'></i>"
    + "</div>"
    + "</div>"
    + "</div>"   
    + "<p class='w3-center'>© " + new Date().getFullYear() + " Fraonds Technologies. All rights reserved.</p>" 
    + "</footer>";